name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    uses: VitifyCode/VitifyCode-CI/.github/workflows/gt-ci.yml@main
    with:
      baseline-name: 'MyGtMcp'
      test-suite-name: 'MyGtMcp Tests'
    secrets: inherit
